name: osg  # Name of your conda environment
channels:
  - defaults
dependencies:
  - python=3.9  # Specify the Python version  
  - pip       
  - pip:
      - numpy
      - open3d   
      - networkx 
      - pillow
      - matplotlib
      - transformers
      - torch
      - torchvision
      - tqdm
      - ipykernel
      - timm==0.9.10
      - fire
      - more_itertools
      - opencv-python==4.9.0.80
      - pyliblzfse