name: osg  # Name of your conda environment
channels:
  - defaults
dependencies:
  - python=3.9  # Specify the Python version
  - numpy       
  - pip         
  - pip:
      - open3d   
      - networkx 
      - pillow
      - matplotlib
      - transformers
      - torch
      - torchvision
      - tqdm
      - ipykernel
      - timm==0.9.10